version: '3.5'

services:
  flaskapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: swa-api
    container_name:  swa-api
    ports:
      - "27991:8000"
    networks:
      - "reverse-proxy"
    depends_on: 
      - mqtt
    restart: unless-stopped
  ui-server:
    build:
      context: ./ui-server
      dockerfile: Dockerfile
    image: swa-ui
    container_name: swa-ui
    ports:
      - "27990:80"
      - "27992:443"
    networks:
      - "reverse-proxy"
    restart: unless-stopped
  mqtt:
      build: 
        context: ./mqtt
        dockerfile: Dockerfile
      image: eclipse-mosquitto
      container_name: swa-mqtt
      networks:
      - "reverse-proxy"
      volumes:
        - type: volume
          source: log
          target: /mosquitto/log
        - type: volume
          source: data
          target: /mosquitto/data

volumes:
  log:
  data:

networks:
  reverse-proxy:
    external: true
  
